### ISSUE TITLE
Plover can't distinguish between S1 (P-) and S2 (K-)

### ISSUE THREAD

**Issue by LukasFrischmuth** [Kaoffie/plover-delta-de#3]
![Temp_Steno_Problem](https://github.com/user-attachments/assets/11a706db-351c-4f25-8d50-ff6a112f9e31)

I've built a keyboard based on following repository: https://github.com/mike-ady/Stenokey

It works fine when debugging it using the Arduino IDE and it works fine with most of the german syllatype module.
However, plover doesn't seem to be able to distinguish between S1 and S2, as both of them print "P", whereas S2 should print "K".

I tried to get to the problem's source, yet I only discovered that it seems to be a problem on plover's side.
The attached screenshot shows that each physical key is connected to its respective digital key.

Do you have any idea how to resolve this issue?

**Comment by YAMEROOOO** [comment]
I have no clue, sorry. If you want to keep chatting feel free to DM me via my Discord.

**Comment by LukasFrischmuth** [comment]
I've found a solution. It was neither a problem with plover nor with syllatype. Instead it was a problem with my keyboard.

A more in-depth solution can be found [here](https://github.com/mike-ady/Stenokey/issues/8).
